### ISSUE TITLE
jqueryify not found by Stitch

### ISSUE THREAD

**Issue by anissen** [maccman/spine.contacts#12]
Following the "usage" guide and running the vanilla code results in the following JavaScript error:

```
Uncaught module jqueryify not found
```

It looks as though the examples are quite dated compared to spine. Too bad as good examples can be a great starting point for learning a new framework...

**Comment by maccman** [comment]
You run npm install?

**Comment by anissen** [comment]
Yes I did. I don't know if its a Windows-only issue. Spine itself works like a charm. It seems like there is some configuration issue with spine.contacts but I haven't been able to locate it. jquerify is install so everything _ought_ to work... but doesn't :P

**Comment by maccman** [comment]
Yes, Hem doesn't work on Windows unfortunately.

**Comment by anissen** [comment]
Hem seems to work perfectly for new projects created with Spine. No matter, I will just use spine.contacts as a reference. Just thought I'd bring attention to the issue to help other people - like myself - trying out the examples and finding that they don't work.

**Comment by anissen** [comment]
You are correct, hem doesn't work on Windows at all. This is quite an obstacle for using Spine in Windows. 
**However**, this tiny fix (https://github.com/maccman/hem/pull/31) corrects the problems I've been having with hem. Yay :)

Any chance for this work-around to get included in the module?
